### ISSUE TITLE
wraping file content

### ISSUE THREAD

**Issue by cevro** [fykosak/astrid#8] opened 2016-04-03 21:35 UTC
Wrap file content as <pre>.
CSS:  `white-space: pre;`

**Comment by Werkov** [comment] 2016-04-03 22:09
Does it relate to issue #7? The problem is that the files are display by simply sending the raw content of the file in the HTTP response (thus you can directly open e.g. PDFs in the broswer). If you meant something different, please extend your reasoning. Thanks.

**Comment by cevro** [comment] 2016-04-04 01:16
> sending the raw content of the file in the HTTP response

Great idea, but except .tex .pdf .csv is sendig file content as text/html.
It would not be better if it sends text/plain?

https://www.w3.org/Protocols/rfc1341/7_1_Text.html

**Comment by Werkov** [comment] 2016-04-12 22:16
Please see my comment at #7 and close this issue if you are fine with that.

**Closed as completed** 2016-04-12 22:32 UTC
Labels: duplicate
